# Generated by Django 4.1.3 on 2022-11-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Anna', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Andersson', max_length=300),
        ),
    ]
