# Generated by Django 4.1.3 on 2022-11-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_student_group_remove_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.CharField(default='', max_length=500)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.CharField(default='', max_length=500)),
                ('points_max_e', models.FloatField()),
                ('points_max_a', models.FloatField()),
                ('points_max_c', models.FloatField()),
                ('set_limit', models.BooleanField(default=False)),
                ('points_grade_e_e', models.FloatField(default=0)),
                ('points_grade_d_e', models.FloatField(default=0)),
                ('points_grade_d_c', models.FloatField(default=0)),
                ('points_grade_c_e', models.FloatField(default=0)),
                ('points_grade_c_C', models.FloatField(default=0)),
                ('points_grade_b_e', models.FloatField(default=0)),
                ('points_grade_b_c', models.FloatField(default=0)),
                ('points_grade_b_a', models.FloatField(default=0)),
                ('points_grade_a_e', models.FloatField(default=0)),
                ('points_grade_a_c', models.FloatField(default=0)),
                ('points_grade_a_a', models.FloatField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
                ('points_e', models.FloatField()),
                ('points_c', models.FloatField()),
                ('points_a', models.FloatField()),
                ('points_diff_max_e', models.FloatField(default=0)),
                ('points_diff_max_c', models.FloatField(default=0)),
                ('points_diff_max_a', models.FloatField(default=0)),
                ('result', models.CharField(max_length=20)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result', to='main.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_result', to='main.assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_result', to='main.student')),
            ],
        ),
    ]
